on:
  schedule:
    - cron:  '55 */6 * * *' # At minute 55 past every 6th hour. Ref https://crontab.guru/examples.html
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: Set up Go
      uses: actions/setup-go@v1
      with:
       go-version: 1.14
    - uses: actions/checkout@v2
    - name: GoGet
      run: go get
    - name: Run
      run: go run main.go
      # env:
      #   WHATEVER_TOKEN: ${{ secrets.YOU_WANT }}
    - uses: mikeal/publish-to-github-action@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # GitHub sets this for you
